/*
 * Copyright (c) 2023-2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const VERTICAL_HEIGHT = 475;

export const DEFAULT_HEIGHT = 532;

export const PC_HEIGHT = 392;

export const FLOD_VERTICAL_HEIGHT = 500;

export const PRIVATE_FIRST_HEIGHT = 419;

export const PRIVATE_SECOND_HEIGHT = 439;

export const FLOD_VERTICAL_HEIGHT_SECOND = 469;

export const FLOD_CROSS_HEIGHT = 419;

export const VERTICAL_OHOS_HEIGHT = 513;

export const CROSS_HEIGHT = 235;

export const COMMEN_HEIGHT = 0;

export const COMMEN_X = 0;

export const VERTICAL_Y = -288;

export const CROSS_Y = -20;

export const COMMEN_Y = 0;

export const COMMEN_Z = 0;

export const INIT_HEIGHT = 159;

export const ADD_HEIGHT = 76;

export const INIT_VERHEIGHT = 143;

export const ADD_VERHEIGHT = 76;

export const FRIST_H = 76;

export const SECOND_H = 152;

export const THIRD_H = 228;

export const FOURTH_H = 304;

export const FIVE_H = 380;

export const SIX_H = 456;

export const RESTRICT = -999;

// '99:59:59.99'
export const STOPTIME = 359999000;

export const BUTTON_MOVE_VERTACIL = -37;

export const BUTTON_MOVE_CROSS = -43;

export const BREAKLG = 70;

export const RESTRICT_HEIGHT = 447;

export const BREAKLG_HEIGHT = 456;

export const FLOD_ALL_HEIGHT = 510;

export const FLOD_BUTTON_MOVE = -60;

export const BUTTON_MOVE_CROSS_OHOS = -85;

export const BUTTON_MOVE_VERTACIL_OHOS = -41;

export const RESTRICT_MAXTIME = '99:59:59.99';