/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const STR_PLACE_HOLDER = '%s';

export const SECOND_IN_MINUTE = 60;

export const MINUTE_IN_HOUR = 60;

export const MILLIS_IN_SECOND = 1000;

export const SECOND_IN_HOUR = SECOND_IN_MINUTE * MINUTE_IN_HOUR;

export const HOURS_IN_ONE_DAY = 24;

export const FIRST_PARAM = '%1$s';

export const SECOND_PARAM = '%2$s';

// 刻度圆环直径占比
export const SCALE_DIAMETER_RATIO = 0.92;

export const CLOCK_SCALE_VALUE = 0.9;

export const DIAL_DIAMETER_RATIO = 1.67;

export const CLOCK_RATIO_FOR_NORMAL = 0.60;

export const CLOCK_RATIO_FOR_LG = 0.60;

export const HALF = 0.5;

export const UPDATE_WIDTH_DELAY = 50;

export const CLOCK_RATIO_FOR_NORMAL_CUSTOM = 0.60;

export const SPECAIL_CLOCK_RATIO_FOR_NORMAL_CUSTOM = 0.70;

export const SPECAIL_CLOCK_TIMER_NORMAL_CUSTOM = 0.70;

export const CLOCK_RATIO_FOR_LG_CUSTOM = 0.50;

// Window Shadow Collection
export const EVENT_ID_WINDOW_SHADOW = 666;

export const EVENT_ID_SWITCH_PAGE = 667;


export interface SizeInfo {
  width: number;
  height: number;
}